# Duarte-Scalper Configuration File

# Trading Settings
trading:
  symbols: ["WINM25", "WDOM25"]
  magic_number: 778899
  robot_name: "DUARTE-SCALPER"
  default_lot_size: 1.0
  max_positions_per_symbol: 3
  
# Risk Management
risk:
  max_risk_per_trade: 0.01  # 1%
  max_daily_loss: 0.03      # 3%
  max_consecutive_losses: 5
  max_position_time_minutes: 10
  cool_down_after_limit_hours: 1

# Data Collection
data:
  historical_months: 6
  tick_collection_interval_ms: 1
  ohlc_timeframes: ["M1"]
  save_interval_hours: 1
  backup_interval_days: 7

# Machine Learning
ml:
  ensemble_weights:
    lstm: 0.40
    xgboost: 0.35
    random_forest: 0.25
  
  training:
    validation_split: 0.2
    epochs: 100
    batch_size: 32
    retrain_interval_days: 1
  
  prediction:
    min_confidence: 0.7
    signal_timeframes: [10, 30, 60, 300]  # seconds

# Communication
communication:
  method: "named_pipes"  # ou "tcp_socket"
  pipe_name: "\\\\.\\pipe\\duarte_scalper"
  timeout_seconds: 1.0
  max_buffer_size: 1024

# Logging
logging:
  level: "INFO"
  max_file_size_mb: 10
  backup_count: 5
  
  files:
    main: "logs/duarte_scalper.log"
    trading: "logs/trading.log"
    data: "logs/data_collection.log"
    model: "logs/model_training.log"

# Paths
paths:
  data_root: "data"
  models_path: "data/models"
  logs_path: "logs"
  config_path: "config"